### ISSUE TITLE
Idea: upgrading "Wisdom" and "Dexterity" as well as Strength

### ISSUE THREAD

**Issue by HomebrewHomunculus** [HomebrewHomunculus/BrogueLite#18]
In Brogue, your only primary character attributes ("stats") are Health and Strength. Health is self-explanatory; Strength increases your damage and defense through increasing the effective enchantment level of weapons and armor (but not that of rings, staves, or wands). 

The game also includes some hidden values which could be considered "secondary attributes". The are never increased permanently in the way that Health and Strength are, only modified by equipment:

* base staff recharge rate: modified by rings of wisdom.
* base charm recharge rate: not modified by any equipment, but included here for completeness. (Rings of reaping give you charges towards charms, but they don't affect the base rate.)
* searching strength: modified by rings of awareness.
* vision radius: modified by rings of light.
* stealth radius: modified by armor and rings of stealth. Also affected by environmental areas of darkness/light, resting (temporarily), and set to 1 while invisible. 
* health regeneration rate: modified by rings of regeneration.
* accuracy and defense: modified by eff. enchantment level and therefore by Strength, but could arguably be considered separate secondary attributes.

There is potential here, if one wanted to go in a slightly different direction, to add ways to modify these secondary attributes. Note that many of these attributes are thematically related to each other and could potentially be linked to classic RPG character attributes (other than Strength).

The following should **not** be taken as a mission statement or plan for the direction of Brogue Lite, only as a fun thought excercise, or potentially an idea to experiment with in other forks.

* If one wanted to add more "class" to the game, these secondary attributes could vary at the beginning of the game (by random selection or by player choice), in certain correlated patterns, and with sufficiently small values as to not unbalance the game. This could be a one-time starting boost only - or, in a more extreme deviation from Brogue, a repeated improvement that replaces the strength progression (i.e. potions of strength replaced by "potions of experience" that boost your class attributes). The starting kits could potentially be tied to different starting equipment as well.
* Or, keeping with classless Brogue, there could be ways to permanently modify these attributes during the game. Consider, for example, a "fountain of experience": a terrain feature that randomly spawns in the dungeon (or at certain intervals). Using a fountain gives the player a one-time choice of upgrading certain attributes. The set of choices could be the same each time, or a randomly chosen subset of all possible upgrades (cf. the altars of Hoplite). The upgrades could even require sacrificing Strength to increase one of the new attributes.

Possible ways to bundle the attributes together:

* "Wisdom" = staff recharge rate (which his currently called wisdom), vision radius, searching strength (awareness)
* "Vitality" = health regeneration rate (and max. Health)
* "Dexterity" = stealth, accuracy (of thrown weapons?)

Benefits of including more permanent upgrade paths:
* More variety in character builds.
* More unpredictability in character builds (if availability is random), or more player freedom (if free choice).
* Potentially more thematic feeling characters, and therefore more player attachment to them and greater engagement of "narrative" players.

Disadvantages:
* Making the game more complex, potentially harder to balance, and less approachable to beginners.
* Breaking the elegant and streamlined design which Brogue is famed for. Making Brogue feel less like Brogue and more like the many other roguelikes out there.
* Potentially introducing "auto-win" builds or no-brainer choices.

Challenges:
* Interactions between player choice and dungeon seeds
* Gameplay balancing for a higher nubmer of variables
* Keeping the game's identity intact

**Comment by MMarki** [comment]
I really like BrogueLite - it's a even more streamlined version of an already streamlined and elegant roguelike. I think adding stats like Wisdom and Dexterity not only compromises Brogue's identity, but the identity of this mod as well.

**Comment by HomebrewHomunculus** [comment]
It's a bad idea, at least for BrogueLite, as MMarki says.
Closing for now.

This repo is now deprecated. Please see the new Brogue Lite repository at:
* https://github.com/HomebrewHomunculus
