### ISSUE TITLE
Is this version going to keep tracking CE?

### ISSUE THREAD

**Issue by pezz** [HomebrewHomunculus/BrogueLite#30]
Hi there,

Just a general question on whether this is going to keep up with CE from 1.1.0 and beyond?

Cheers.

**Comment by HomebrewHomunculus** [comment]
Hi! Thanks for the interest in the game!

The plan is indeed to keep up-to-date with CE. However, there was a little git tangle due to the way this repository was originally set up.

I've fixed it in my fork of BrogueCE here: https://github.com/HomebrewHomunculus/BrogueCE/pull/2

That branch seems to work - now I just need to decide whether it's better to rename that repository to BrogueLite and delete this one, or to rewrite this repository's history with that one's (if it's even possible).

**Comment by tmewett** [comment]
You should be able to add upstream BrogueCE as a remote to your clone of this repo. Then I *think* you can fetch the entire CE history into it. (There will be branch name clashes so you'll have to *only* fetch and leave them as remote branches.) After that you can rebase your Lite branch changes onto the actual CE commit which you based on. That way you preserve both histories, and can continue using this repo.

**Comment by HomebrewHomunculus** [comment]
I've set up a [new repo](https://github.com/HomebrewHomunculus/BrogueCE/) a while back. It has v1.10 changes merged, and you can compile it, but I'm not quite ready to make an official release yet. Still need to resolve some conflicts to merge v1.10.1 from upstream. More detailed todo-list here:

https://github.com/HomebrewHomunculus/BrogueCE/issues/5

Completing what's outlined there should bring the proper resolution to your question here.

**Comment by HomebrewHomunculus** [comment]
Also, @pezz - the new repo allows me to easily merge new changes from BrogueCE. This massive chore was only a one-time thing. So, hopefully, there will be no more huge delays like this with tracking CE in the future. Apologies for the wait!

**Comment by Nanoc-ice** [comment]
Cloned the source and compiled clean on Mac (Catalina).  I don't know about others, but I REALLY like what you have done with this.  It fits my rogue like playing style (and frequency) perfectly!!  Thanks for making it!

**Comment by pezz** [comment]
Awesome stuff. I've compiled current master on Arch Linux with no worries.

I'll wait till you tag a new official release before I update the package in the AUR.

Cheers.

**Comment by HomebrewHomunculus** [comment]
Hi, sorry for the wait. The new repo is now up to date with Brogue CE 1.11.1 and I've made a pre-release with Linux artifacts available. Unfortunately, the Github Actions build pipeline has broken.

Please see more here:
* https://github.com/HomebrewHomunculus/BrogueCE/issues/5#issuecomment-1251471322
* https://github.com/HomebrewHomunculus/BrogueCE/releases/tag/Lite-1.11.1-RC1

**Comment by HomebrewHomunculus** [comment]
I should mention, I didn't do much testing on that pre-release, which is not really the standard I aim for. Apologies if there are any crashes.
